### ISSUE TITLE
Get AsyncFetchWrapper to print debug statements

### ISSUE THREAD

**Issue by chandru89new** [afsheen-01/vercel-ts-sdk#13]
All our functions are kind of black-boxed once users start using them (or we start testing them). 

That means, for instance, if someone uses the `getUserTokens` function, there is no easy-way to verify/check which API endpoint it calls, what parameters it passes etc.

This will get progressively complex as we start writing functions that make POST requests where request body is involved.

So, we need to be able to have a "debug-mode" where things like "which endpoint did it make a call to?", "what data did it pass in the HTTP request", "what was the actual response object returned?", "what token was used to make this call?" etc should be logged when the function runs.

To do this, however, the asyncFetchWrapper function needs to _know_ what `url` was called, what `data` was used etc. Right now this is not possible because the asyncFetchWrapper simply takes a lambda and runs it. What needs to happen is that asyncFetchWrapper should have the same interface as the `fetch`. Then, it will have access to all the params and can debug.

**Comment by chandru89new** [comment]
There's still some more work to be done on this (eg, printing the data that was sent to a request etc). So we'll keep this open for a while.

**Comment by afsheen-01** [comment]
gotcha
