### ISSUE TITLE
Abstract one more level so we dont have to pass headers, methods etc in every call

### ISSUE THREAD

**Issue by chandru89new** [afsheen-01/vercel-ts-sdk#17]
Right now, we're manually adding "method" and "headers" into every call to the asyncFetchWrapper function.

We will be writing hundreds of functions (which make calls to the API) and that means we'd be repeating this pattern over.

We could abstract these parts out to make it much more simpler to make these API calls.

**Comment by afsheen-01** [comment]
can we write a utils function to generate headers for us?
